databases:
  - name: bookmyseat-db
    plan: free

services:
  - type: web
    name: bookmyseat
    runtime: python
    plan: free

    buildCommand: "./build.sh"
    startCommand: "gunicorn bookmyseat.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: bookmyseat-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
